### ISSUE TITLE
Error when using in Azure Automation Account

### ISSUE THREAD

**Issue by AlexErl** [Agazoth/PSParquet#11]
Try to use export-parquet in an Azure Automation Account. Imported the module in a custom powershell 7.2 environment.
Error:
System.Management.Automation.CommandNotFoundException: The 'Export-Parquet' command was found in the module 'PSParquet', but the module could not be loaded.

Locally everything is working fine.

Reproduceable with a new runbook with the examples delivered in the "help Export-Parquet -examples"

**PowerShell info from Automation Account environment
Name                           Value
----                           -----
PSVersion                      7.2.0
PSEdition                      Core
GitCommitId                    7.2.0
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

**Comment by Agazoth** [comment]
Hi @AlexErl - thanks for trying out the module.

It has been a long time since I worked with Azure Automation Accounts. I remeber the reason for leaving them behind was old binaries and all the very old preloaded modules causing grief. I suspect you are experiencing something similar.

In your case running `Import-Module PSParquet -Verbose -Debug -Force` would procude this error:

`Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.`

This usualy indicates, that older versions of the dlls used my PSParquet, are already in use elsewhere in the runspace.

That narrowes the issue down to figuring out, which one of these files are already in use in an earlier version in the runspace:

```
Name                                    $_.versioninfo.fileversion
----                                    --------------------------
Apache.Arrow.dll                        11.0.0.0
IronCompress.dll                        1.5.2
Microsoft.Data.Analysis.dll             0.2100.124.6804
Microsoft.IO.RecyclableMemoryStream.dll 3.0.0.0
Microsoft.ML.DataView.dll               3.0.124.6804
Parquet.dll                             4.24.0
PSParquet.dll                           1.0.0.0
Snappier.dll                            1.1.6.0
System.Management.Automation.dll        5.1.1
ZstdSharp.dll                           0.8.1.0
nironcompress.dll
```

I have not tried this kind of investigation in Azure Automation Accounts, but I would appreciate any insights on the subject.

**Comment by AlexErl** [comment]
Hi,

I have checked all the dlls you mentioned and it looks to me like the “System.Management.Automation.dll” is the problem.

DLL: System.Management.Automation.dll, Version: 7.2.0.500, Path: C:\app\runtimes\unix\lib\net6.0\System.Management.Automation.dll
DLL: System.Management.Automation.dll, Version: 7.2.0.500, Path: C:\app\runtimes\win\lib\net6.0\System.Management.Automation.dll
DLL: System.Management.Automation.dll, Version: 7.2.20.500, Path: C:\Program Files\powershell\.store\powershell.windows.x64\7.2.20\powershell.windows.x64\7.2.20\tools\net6.0\any\System.Management.Automation.dll
DLL: System.Management.Automation.dll, Version: 5.1.1, Path: C:\usr\src\PSModules\Automation.Sandbox.AssetManagement.Cmdlets\System.Management.Automation.dll
DLL: System.Management.Automation.dll, Version: 5.1.1, Path: C:\usr\src\PSModules\PSParquet\bin\System.Management.Automation.dll
DLL: System.Management.Automation.dll, Version: 5.1.1, Path: C:\usr\src\tmp\9b2bc6fc-767e-4db9-8ea8-68083592f09a\bin\System.Management.Automation.dll
DLL: System.Management.Automation.dll, Version: 6.1.7600.16385, Path: C:\Windows\assembly\GAC_MSIL\System.Management.Automation\1.0.0.0__31bf3856ad364e35\System.Management.Automation.dll
DLL: System.Management.Automation.dll, Version: 10.0.17763.5933, Path: C:\Windows\Microsoft.NET\assembly\GAC_MSIL\System.Management.Automation\v4.0_3.0.0.0__31bf3856ad364e35\System.Management.Automation.dll
DLL: System.Management.Automation.dll, Version: 6.1.7600.16385, Path: C:\Windows\WinSxS\msil_system.management.automation_31bf3856ad364e35_1.0.0.0_none_6340379543bd8a03\System.Management.Automation.dll
DLL: System.Management.Automation.dll, Version: 10.0.17763.5933, Path: C:\Windows\WinSxS\msil_system.management.automation_31bf3856ad364e35_10.0.17763.5933_none_1295531ff9f25bd4\System.Management.Automation.dll

My Win11 machine shows a different version:
DLL: System.Management.Automation.dll, Version: 7.4.5.500, Path: C:\Program Files\PowerShell\7\System.Management.Automation.dll

Perhaps you have an idea how to solve that issue.
Thanks Alex

**Comment by Agazoth** [comment]
@AlexErl I am quite sure the built-in Azure run environment will not be udpated to the new version in the near future.

I have had success with deploying a hybrid worker (Ubuntu 22.04 LTS) and running PSParquet from there via Azure Automation.

![{269FB92E-FAD1-47C6-840B-4613AA152B47}](https://github.com/user-attachments/assets/c0e3963b-44fb-4a34-9cc4-7ad70f39d2b7)


![{252E24D9-F290-4F7D-866F-751AFD2EA80C}](https://github.com/user-attachments/assets/2cb599a9-4e9d-41fe-95df-6599456e211c)


It is also possible to create a PowerShell Function App and run PSParquet from there.

**Comment by AlexErl** [comment]
Tested with a Windows Hybrid Worker machine and it's working fine.
