### ISSUE TITLE
System.IO.FileInfo error

### ISSUE THREAD

**Issue by HyperFail** [Agazoth/PSParquet#5]
I have installed this module using 

`Install-Module PSParquet`

I have created a data pscustomobject. Running the below command results in this error:

`Export-Parquet -InputObject $GatewayObj -Path "c:\temp\file.parquet"`

![image](https://github.com/Agazoth/PSParquet/assets/83844234/0a8df5a2-4c0f-44fb-aaa7-69329125f030)

**Comment by Agazoth** [comment]
Please update your issue with your system information.

Are you using Windows PowerShell? The module requires PowerShell 7.x.

**Comment by Agazoth** [comment]
Cloding. No feedback
